# Generated by Django 4.2.7 on 2024-12-12 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formularioinspeccion',
            name='inspeccion',
        ),
        migrations.RemoveField(
            model_name='formularioinspeccion',
            name='observacion',
        ),
        migrations.CreateModel(
            name='InspeccionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspeccion', models.CharField(choices=[('M', 'Malo'), ('R', 'Regular'), ('B', 'Bueno')], max_length=1)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componente')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formularioinspeccion')),
            ],
        ),
    ]
