# Generated by Django 4.2.7 on 2025-01-11 17:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_formularioinspeccion_inspeccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiones',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='encuestador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encuestador', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
